### PR TITLE
Use npm.cmd for windows

### LINKED ISSUE #2: AppVeyor buid fails
Hi!

My build on AppVeyor fails with:
```
> chatinder@1.4.5 postinstall C:\projects\chatinder
> is-ci 'ci:skip' 'install:types'
internal/child_process.js:317
    throw errnoException(err, 'spawn');
    ^
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:317:11)
    at Object.exports.spawn (child_process.js:471:9)
    at run (C:\projects\chatinder\node_modules\is-ci-cli\cli.js:11:23)
    at Object.<anonymous> (C:\projects\chatinder\node_modules\is-ci-cli\cli.js:25:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

### PR DESCRIPTION
**Pull request by adierkens**
Windows needs the `.cmd` ending for the `npm` binary.
Also [detached](https://nodejs.org/api/child_process.html#child_process_options_detached) on Windows makes the process open a new terminal, and doesn't do the right thing with STDOUT/STDERR, so I fixed that. 

Tested locally on my Windows box, and it seems to be okay. OSX still worked as before.

is-ci-cli test

Hopefully closes #2

### CODE REVIEW

File: cli.js [hunk 1]
```diff
@@ -3,19 +3,21 @@
 'use strict';
 const childProcess = require('child_process');
 const isCi = require('is-ci');
+const isWindows = process.platform === 'win32';
+const npmExec = isWindows ? 'npm.cmd' : 'npm'
```
Comment (YellowKirby) [inline cli.js]: Should we still (try to) use the `npm_execpath` env var? Seems like we'd need it if we wanted to also support yarn or an `npm` that isn't part of PATH. Maybe just use it if not on Windows?

Comment (adierkens) [inline cli.js]: Good call. I updated it to use `npm_execpath` on non-windows
